using AutoBZOC, Unitful, LinearAlgebra
trG_auxfun(v, G1, G2) = tr(G1) + tr(G2)

mkpath("crossover")
make(;
    target=:crossover,
    nsample=1,
    use_cache=true,
    cache_dir="crossover",
    figure_path = "figs_t2g",
    model=AutoBZOC.t2g_model,
    chempot = AutoBZOC.findchempot,
    config_quad_breakeven = [
        (;
            config_bench = (;
                Ω = 0.0u"eV",
                auxfun = trG_auxfun,
                aux_inner_only=false,
                rescale_inner = false,
                rtol_σ = 0.0,
                quad_σ_k = AutoBZOC.IAI(AutoBZOC.AuxQuadGKJL(order=4)),
                quad_σ_ω = AutoBZOC.AuxQuadGKJL(order=4),
            ),
            series_atol_σ = AutoBZOC.AuxValue.(1e-5 * AutoBZOC.extrapolate_dc_scaling2(;
                extrap_T=u"K" * (2.0 .^ range(10, 8, step=-0.5)),
                # extrap_T=u"K" * (2.0 .^ range(10, 4, step=-0.5)),
                series_T=u"K" * (2.0 .^ range(7, 6.5, step=-0.25)),
                quad_σ_k=AutoBZOC.AutoPTR(nmin=1, nmax=typemax(Int)),
                quad_σ_ω=AutoBZOC.AuxQuadGKJL(order=4),
                atol_σ = (2pi)^3 * 1e-5u"Å^-1",
            ), (2pi)^3*1e-2u"eV^-1 * Å^-3"),
            series_T = u"K" * (2.0 .^ range(10, 8, step=-0.5)),
            # series_T = u"K" * (2.0 .^ range(10, 4, step=-0.5)),
            plot_kws = (; label=AutoBZOC.L"$\Omega=0$ eV, IAI" #= (GK=4), aux atol asy 1e-5"=#, marker=:rect, markersize=60, strokewidth=0, color=AutoBZOC.Makie.wong_colors()[1]),
        ),
        (;
            config_bench = (;
                Ω = 0.0u"eV",
                auxfun = nothing,
                atol_σ = 1e-1u"Å^-1",
                rtol_σ = 0.0,
                quad_σ_k = AutoBZOC.AutoPTR(nmin=1, nmax=typemax(Int)),
            ),
            series_atol_σ = 1e-5 * AutoBZOC.extrapolate_dc_scaling2(;
                extrap_T=u"K" * (2.0 .^ range(10, 8.0, step=-0.5)),
                # extrap_T=u"K" * (2.0 .^ range(10, 6.0, step=-0.5)),
                series_T=u"K" * (2.0 .^ range(7, 6.5, step=-0.25)),
                quad_σ_k=AutoBZOC.AutoPTR(nmin=1, nmax=typemax(Int)),
                quad_σ_ω=AutoBZOC.AuxQuadGKJL(order=4),
                atol_σ = (2pi)^3 * 1e-5u"Å^-1",
            ),
            series_T = u"K" * (2.0 .^ range(10, 8.0, step=-0.5)),
            # series_T = u"K" * (2.0 .^ range(10, 6.0, step=-0.5)),
            plot_kws = (; label=AutoBZOC.L"$\Omega=0$ eV, PTR" #= atol asy 1e-5" =#, marker=:rect, markersize=40, color=:transparent, strokewidth=10, strokecolor=AutoBZOC.Makie.wong_colors()[1]),
        ),
        (;
            config_bench = (;
                Ω = 0.4u"eV",
                auxfun = trG_auxfun,
                aux_inner_only=true,
                rescale_inner = true,
                rtol_σ = 0.0,
                quad_σ_k = AutoBZOC.IAI(AutoBZOC.AuxQuadGKJL(order=4)),
                quad_σ_ω = AutoBZOC.AuxQuadGKJL(order=4),
            ),
            series_atol_σ = fill(AutoBZOC.AuxValue(2e-4u"Å^-1", (2pi)^3*1e-2u"eV^-1 * Å^-3"), length(range(10, 8, step=-0.5))),
            # series_atol_σ = fill(AutoBZOC.AuxValue(2e-4u"Å^-1", (2pi)^3*1e-2u"eV^-1 * Å^-3"), length(range(10, 4, step=-0.5))),
            series_T = u"K" * (2.0 .^ range(10, 8, step=-0.5)),
            # series_T = u"K" * (2.0 .^ range(10, 4, step=-0.5)),
            plot_kws = (; label=AutoBZOC.L"$\Omega=0.4$ eV, IAI" #= (GK=4) aux_ω atol 2e-4"=#, marker=:circle, markersize=60, strokewidth=0, color=AutoBZOC.Makie.wong_colors()[2]),
        ),
        (;
            config_bench = (;
                Ω = 0.4u"eV",
                auxfun = nothing,
                rtol_σ = 0.0,
                quad_σ_k = AutoBZOC.AutoPTR(nmin=1, nmax=typemax(Int)),
                quad_σ_ω = AutoBZOC.AuxQuadGKJL(order=4),
            ),
            series_atol_σ = fill(2e-4u"Å^-1", length(range(10, 8.0, step=-0.5))),
            # series_atol_σ = fill(2e-4u"Å^-1", length(range(10, 6.0, step=-0.5))),
            series_T = u"K" * (2.0 .^ range(10, 8.0, step=-0.5)),
            # series_T = u"K" * (2.0 .^ range(10, 6.0, step=-0.5)),
            plot_kws = (; label=AutoBZOC.L"$\Omega=0.4$ eV, PTR" #= atol 1e-4" =#, marker=:circle, markersize=40, color=:transparent, strokewidth=10, strokecolor=AutoBZOC.Makie.wong_colors()[2]),
        ),
        (;
            config_bench = (;
                Ω = 0.75u"eV",
                auxfun = trG_auxfun,
                aux_inner_only=true,
                rescale_inner = true,
                rtol_σ = 0.0,
                quad_σ_k = AutoBZOC.IAI(AutoBZOC.AuxQuadGKJL(order=4)),
                quad_σ_ω = AutoBZOC.AuxQuadGKJL(order=4),
            ),
            series_atol_σ = fill(AutoBZOC.AuxValue(1e-4u"Å^-1", (2pi)^3*1e-2u"eV^-1 * Å^-3"), length(range(10, 8, step=-0.5))),
            # series_atol_σ = fill(AutoBZOC.AuxValue(1e-4u"Å^-1", (2pi)^3*1e-2u"eV^-1 * Å^-3"), length(range(10, 4, step=-0.5))),
            series_T = u"K" * (2.0 .^ range(10, 8, step=-0.5)),
            # series_T = u"K" * (2.0 .^ range(10, 4, step=-0.5)),
            plot_kws = (; label=AutoBZOC.L"$\Omega=0.75$ eV, IAI"#=  (GK=4) aux_ω atol 1e-4"=#, marker=:diamond, markersize=60, strokewidth=0, color=AutoBZOC.Makie.wong_colors()[3]),
        ),
        (;
            config_bench = (;
                Ω = 0.75u"eV",
                auxfun = nothing,
                rtol_σ = 0.0,
                quad_σ_k = AutoBZOC.AutoPTR(nmin=1, nmax=typemax(Int)),
                quad_σ_ω = AutoBZOC.AuxQuadGKJL(order=4),
            ),
            series_atol_σ = fill(1e-4u"Å^-1", length(range(10, 8.0, step=-0.5))),
            # series_atol_σ = fill(1e-4u"Å^-1", length(range(10, 6.0, step=-0.5))),
            series_T = u"K" * (2.0 .^ range(10, 8.0, step=-0.5)),
            # series_T = u"K" * (2.0 .^ range(10, 6.0, step=-0.5)),
            plot_kws = (; label=AutoBZOC.L"$\Omega=0.75$ eV, PTR" #= atol 1e-4"=# , marker=:diamond, markersize=40, color=:transparent, strokewidth=10, strokecolor=AutoBZOC.Makie.wong_colors()[3]),
        ),
    ],
    config_scaling_breakeven = [
        # (; x=10.0 .^ (-3.5:0.1:-1.0), fun = a -> log(0.25/a)^4, factors=(4e1, 2e8), plot_kws=(; label = "log(1/4η)⁴",)),
        (; x=10.0 .^ (-2.25:0.1:-0.5), fun = a -> log(1/a)/a^3, factors=(8e-5, 5e2), plot_kws=(; color = :black, linestyle=:dot, label = AutoBZOC.L"\log(1/\eta)/\eta^3",)),
        (; x=10.0 .^ (-3.5:0.1:-0.5), fun = a -> log(1/a)^4, factors=(8e-1, 4e6), plot_kws=(; color=:black, linestyle=:dashdot, label = AutoBZOC.L"\log^4(1/\eta)",)),
        # (; x=10.0 .^ (0.1:0.1:1), fun = a -> a^4, factors=(8e-1, 4e6), plot_kws=(; color=:black, linestyle=:dot, label = AutoBZOC.L"\log(1/\eta)^4",)),
        # (; x=10.0 .^ (0.1:0.1:1), fun = a -> a^5, factors=(4e-1, 0.9e6), plot_kws=(; color=:black, linestyle=:dashdot, label = AutoBZOC.L"\log(1/\eta)^5",)),
        # (; x=10.0 .^ (0.1:0.1:1), fun = a -> a^5, factors=(4e-0, 2e7), plot_kws=(; color=:black, linestyle=:dashdot, label = AutoBZOC.L"\log(1/\eta)^5",)),
        # (; x=10.0 .^ (0.1:0.1:1), fun = a -> a^6, factors=(4e-2, 2e5), plot_kws=(; color=:red, linestyle=:dashdot, label = AutoBZOC.L"\log(1/\eta)^6",)),
    ],
    theme = merge(AutoBZOC.theme_latexfonts(), AutoBZOC.Theme(; fontsize = 24), AutoBZOC.default.theme,),
    limits_t = ((3e-4, 8e-1), (1.1e-2, 9e3)),
    limits_n = ((3e-4, 8e-1), (3e4, 5e10)),
)